### ISSUE TITLE
Wireframes do projeto

### ISSUE THREAD

**Issue by fmondaini** [concretesolutions/Cantina-Web#2]
O projeto ainda está em branco. Precisamos definir as páginas de escolha de produto, itens consumidos, pagamentos efetuados, pagamentos pendentes, etc.

**Comment by raphaelpor** [comment]
Vamos começar pelo Wireframe da parte administrativa.
Veremos isso ainda hoje.
:wink:

**Comment by raphaelpor** [comment]
Done.
